/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [TimeTableDesigner]    Script Date: 2018. 04. 10. 20:29:11 ******/
CREATE DATABASE [TimeTableDesigner]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeTable', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TimeTable.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimeTable_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TimeTable_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TimeTableDesigner] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeTableDesigner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeTableDesigner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeTableDesigner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeTableDesigner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimeTableDesigner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeTableDesigner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET RECOVERY FULL 
GO

ALTER DATABASE [TimeTableDesigner] SET  MULTI_USER 
GO

ALTER DATABASE [TimeTableDesigner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeTableDesigner] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeTableDesigner] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeTableDesigner] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimeTableDesigner] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeTableDesigner] SET QUERY_STORE = OFF
GO

USE [TimeTableDesigner]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TimeTableDesigner] SET  READ_WRITE 
GO


